import {
  LayoutDashboard,
  Users,
  GraduationCap,
  UserRound,
  Contact,
  ClipboardList,
  Building2,
  FileBarChart,
  CalendarDays,
  FileText,
  MessageSquare,
  Megaphone,
  ScrollText,
  Settings,
  MessageCircle,
  ListChecks,
  BookOpen,
  FolderOpen,
  Target,
  Trophy,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  LayoutDashboard,
  Users,
  GraduationCap,
  UserRound,
  Contact,
  ClipboardList,
  Building2,
  FileBarChart,
  CalendarDays,
  FileText,
  MessageSquare,
  Megaphone,
  ScrollText,
  Settings,
  MessageCircle,
  ListChecks,
  BookOpen,
  FolderOpen,
  Target,
  Trophy,
};
